### ISSUE TITLE
The parameter is incorrect.

### ISSUE THREAD

**Issue by herrblitzkrieg** [M2Team/NanaZip#342]
Using the latest NanaZip Preview and 'The parameter is incorrect' error message shows whenever I try to compress a folder with Lizard even though I left the parameters box empty. Same thing happens when trying to use fast LZMA2. Basically most of algorithms advertised. 

However when attempting the same thing in 7-Zip-ZS everything works as planned.

**Comment by dinhngtu** [comment]
Lizard compression levels are broken in 2.0.450 but seem fixed in Preview (3.0.756). If you use 3.0.756 try changing the compression level to any available one and the problem should go away.

**Comment by herrblitzkrieg** [comment]
I just confirmed that the problem persists in Preview (3.0.756). The issue is happening with every algorithm advertised.

**Comment by dcog989** [comment]
I'm seeing the same - creating an archive (either via Windows context menu or NanaZip interface) using 7z archive format and any compression method produces **"The paramater is incorrect.**

It had been working OK but I have been trying all combinations of compression method / level, block size, memory usage, etc. so it seems something broke while I was doing this testing.

I then deleted `~users\AppData\Local\Packages\40174MouriNaruto.NanaZipPreview_gnj4mf6z9tkrc\SystemAppData\Helium` and problem solved!

I can send the old 'Helium' folder  if any use for debugging?

**Comment by dinhngtu** [comment]
> I'm seeing the same - creating an archive (either via Windows context menu or NanaZip interface) using 7z archive format and any compression method produces **"The paramater is incorrect."**
> 
> It had been working OK but I have been trying all combinations of compression method / level, block size, memory usage, etc. so it seems something broke while I was doing this testing.
> 
> I then deleted `~users\AppData\Local\Packages\40174MouriNaruto.NanaZipPreview_gnj4mf6z9tkrc\SystemAppData\Helium` and problem solved!
> 
> I can send the old 'Helium' folder if any use for debugging?

Sounds like NanaZip's internal Registry was corrupted somehow. The old 'Helium' folder would be very useful.

**Comment by dcog989** [comment]
My (corrupted?) Helium folder - [xHelium.zip](https://github.com/M2Team/NanaZip/files/13855202/xHelium.zip)

**Comment by dinhngtu** [comment]
![Untitled](https://github.com/M2Team/NanaZip/assets/1257909/5951dd69-92a1-4260-9b9f-9adfbdfc91ec)
It's this `MemUse64` value that caused it. There seems to be a bug in parsing the value.

**Comment by dcog989** [comment]
Confirmed. "* 80%" = success. Any other value in 'Memory usage for compressing' = failure ('parameter incorrect').

Thanks @dinhngtu
