### ISSUE TITLE
Various graphical issues

### ISSUE THREAD

**Issue by Leo40Git** [M2Team/NanaZip#405]
![image](https://github.com/M2Team/NanaZip/assets/7997354/d61390af-76bf-4dad-abb8-ee908d85a9bc)
![image](https://github.com/M2Team/NanaZip/assets/7997354/d14c8b6f-100b-4a75-bbb0-615dd72dad2b)
![image](https://github.com/M2Team/NanaZip/assets/7997354/80edfdd6-d3db-472b-a1ca-2956ae35c319)

Seems like the new theme doesn't agree with me.

**Comment by graphixillusion** [comment]
Same for me. Already reported here:

https://github.com/M2Team/NanaZip/issues/402#issuecomment-2125631395

**Comment by Chaython** [comment]
The new theme doesn't seem to support grid lines

**Comment by Merowinger86** [comment]
This looks wrong to me.
![Zwischenablage_05-23-2024_01](https://github.com/M2Team/NanaZip/assets/104984893/573f4877-e3c3-4db8-b7c1-0d6dceb92418)

**Comment by d5aqoep** [comment]
It feels like Mica is not needed. Just default black would work just fine.

**Comment by MouriNaruto** [comment]
XAML tooltips issue should be fixed in https://github.com/M2Team/NanaZip/commit/2603e8e373e23c38c37a5fc1b243970796109e74.

But other issues need to do some further research.

Kenji Mouri

**Comment by Leo40Git** [comment]
The tooltips were indeed fixed, but the odd black spots in text are still present.  
Additionally, the "up" icon now has a solid white background in dark mode.
![image](https://github.com/M2Team/NanaZip/assets/7997354/adfa36cf-f3a9-4943-b19e-175d1fe814d7)

Windows version is 10.0.22631.3593 (Windows 11 23H2).

**Comment by MouriNaruto** [comment]
@Leo40Git 

For the "up" icon, it's a known issue. But this will be solved after replacing that with XAML Islands in future releases.

The odd black spots in the text are caused by your environment‘s DWM because NanaZip uses DWM extended margin to achieve the full mica dark mode. I think this will be solved after replacing legacy UI parts with XAML Islands in future releases.

From your screenshot, the text font is sharp. It should not be a big issue for use daily.

Kenji Mouri

**Comment by rahaaatul** [comment]
also this:

![image](https://github.com/M2Team/NanaZip/assets/86149861/233c14cd-a7a9-46c2-a8d2-e5837ac9c1a8)

**Comment by WhatDamon** [comment]
some graphical problems has been solved in recent build
and the others, most of them are not nanazip's problem but win32, like white board around button
it might be fix in the future, with full xaml islands gui

**Comment by HackZy01** [comment]
![image](https://github.com/user-attachments/assets/e172ccef-edda-4dfe-97f0-1056870b4299)
it's still very broken in dark mode, both with mica enabled and disabled

**Comment by MouriNaruto** [comment]
These issues should have been fixed at least since NanaZip 6.0.

Open a new issue if you meet similar issues.

Kenji Mouri
