### ISSUE TITLE
'Open archive' option opens NanaZip in background

### ISSUE THREAD

**Issue by wodnikk** [M2Team/NanaZip#86]
NanaZip opens in background when using 'Open archive' option in from context menu.

Screenshot of 7-Zip:
![Screenshot (6)](https://user-images.githubusercontent.com/22603225/147753687-f9c670a5-d619-42f7-8a3d-73cba55d00c0.png)

And Nana:
![Screenshot (7)](https://user-images.githubusercontent.com/22603225/147753727-05957d6e-b786-47f5-b6e9-fedb54346a65.png)

**Comment by MouriNaruto** [comment]
It's a known issue from Windows MSIX packaging.

https://github.com/microsoft/terminal/issues/6611

I will track the solution.

Kenji Mouri

**Comment by soredake** [comment]
For the record, this problem is fixed in windows terminal.

**Comment by modz2014** [comment]
When you right click on a directory you want it to open when you right click anywhere that would mean it needs to implement the background

**Comment by soredake** [comment]
I'm not sure what exactly fixed it (recent windows updates maybe) but NanaZip no longer opens in background now.

**Comment by DevLung** [comment]
> I'm not sure what exactly fixed it (recent windows updates maybe) but NanaZip no longer opens in background now.

For me on Win10 it still opens behind the file explorer window.

**Comment by soredake** [comment]
Seems this is fixed only on windows 11 for now.

**Comment by soredake** [comment]
https://github.com/files-community/Files/issues/14978#issuecomment-2217318092

**Comment by LyndonGingerich** [comment]
I'm still seeing it opening behind the Windows Explorer window on Windows 11.

**Comment by ctlp** [comment]
目前这个bug仍然存在，系统为win10专业版22h2

**Comment by soredake** [comment]
https://github.com/files-community/Files/pull/16050

**Comment by soredake** [comment]
With 3.1 update, nanazip finally consistently (after 5 reboots) opens in foreground, could someone else confirm this?

**Comment by sannkyu831** [comment]
> With 3.1 update, nanazip finally consistently (after 5 reboots) opens in foreground, could someone else confirm this?

No,this bug still exists, the system is win10 professional version 22h2

**Comment by LyndonGingerich** [comment]
> I'm still seeing it opening behind the Windows Explorer window on Windows 11.

Now I'm seeing NanaZip open in front.
